name: njktest2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_redux: ^0.10.0
  redux: ^5.0.0
  redux_epics: ^0.15.1
  http: ^1.2.2
  intl: ^0.19.0
  jsonata_flutter: ^0.0.2
  flutter_secure_storage: ^9.2.2
  one_context: ^4.0.0
  icons_plus: ^5.0.0
  authwebview: ^1.0.0
  rappider_flutter_widgets:
    git: https://github.com/rappiderorg/rapider-flutter-widgets.git



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
